### ISSUE TITLE
Data Sources tracker

### ISSUE THREAD

**Issue by timkpaine** [timkpaine/pyEX#54]
# Data Points
- [x] Market Macro indicators
- [x] Stock points

# Stocks
- [x] Advanced Stats
- [x] Balance Sheet
- [x] Batch Requests
- [x] Book
- [x] Cash Flow
- [x] Collections
- [x] Company
- [x] Delayed Quote
- [x] Dividends
- [x] Earnings
- [x] Earnings Today
- [x] Effective Spread
- [x] Estimates
- [x] Financials
- [x] Fund Ownership
- [x] Historical Prices
- [x] Income Statement
- [x] Insider Roster
- [x] Insider Summary
- [x] Insider Transactions
- [x] Institutional Ownership
- [x] Intraday Prices
- [x] IPO Calendar
- [x] Key Stats
- [x] Largest Trades
- [x] List
- [x] Logo
- [x] Market Volume (U.S.)
- [x] News
- [x] OHLC
- [x] Open / Close Price
- [x] Options
- [x] Peers
- [x] Previous Day Price
- [x] Price
- [x] Price Target
- [x] Quote
- [ ] Recommendation Trends
- [x] Sector Performance
- [x] Splits
- [ ] Upcoming Events
- [x] Volume by Venue

# Alternative
- [x] Crypto
- [x] Social Sentiment
- [x] CEO Compensation

# Reference
- [x] Symbols
- [x] IEX Symbols
- [x] International Symbols
- [x] International Exchanges
- [x] U.S. Exchanges
- [x] U.S. Holidays and Trading Dates
- [x] Sectors
- [x] Tags
- [x] Mutual Fund Symbols
- [x] OTC Symbols
- [x] FX Symbols
- [x] Options Symbols
- [ ] Commodities Symbols In Dev
- [ ] Bonds Symbols In Dev
- [ ] Crypto Symbols In Dev

# Forex / Currencies
- [ ] Exchange Rates

# Investors Exchange Data
- [x] TOPS
- [x] Last
- [x] DEEP
- [x] DEEP Auction
- [x] DEEP Book
- [x] DEEP Operational Halt Status
- [x] DEEP Official Price
- [x] DEEP Security Event
- [x] DEEP Short Sale Price Test Status
- [x] DEEP System Event
- [x] DEEP Trades
- [x] DEEP Trade Break
- [x] DEEP Trading Status
- [ ] Listed Regulation SHO Threshold Securities List In Dev
- [ ] Listed Short Interest List In Dev
- [ ] Stats Historical Daily In Dev
- [x] Stats Historical Summary
- [x] Stats Intraday
- [x] Stats Recent
- [x] Stats Records

# API System Metadata
- [x] Status
